# For more details about the configuration, please see
# http://dev.bukkit.org/bukkit-plugins/booksuite/pages/default-config/
# 

###  PRINTING PRESS  ###
# Set to false to globally disable the use of printing presses.
enable-printing-presses: true

###  ERASER  ###
# Same deal as presses.
enable-erasers: true

###  ALIASES  ###
# Aliases are used when signing and manipulating books.
# 
# This allows players to sign books as <team prefix><display name><team suffix>.
# 
# N.B. To support prefix and suffix changes, when checking if the player is an author, containing the display name is enough.
# This means the user "Minecraft" will be able to unsign books by the user "123Minecraft123"
# 
# N.B. This does not support Vault or any other such plugin, only vanilla Minecraft teams.
enable-aliases: true
