name: BookSuite

main: com.github.jikoo.booksuite.BookSuite
version: 4.0.2
author: Adam Gunn (Jikoo)
authors: [Ted Meyer (tmathmeyer)]
description: A large collection of book-related functions.
website: http://dev.bukkit.org/bukkit-plugins/booksuite/

permissions:
 booksuite.admin:
  description: Everything bookish and sweet!
  default: op
  children:
   booksuite.free: true
   booksuite.command.admin: true
   booksuite.block.erase.other: true
   booksuite.sign: true
 booksuite.default:
  description: Average Joe's permissions.
  default: true
  children:
   booksuite.standard:
    default: true
    children:
     booksuite.copy.default: true
     booksuite.command.default: true
     booksuite.mail.default: true
     booksuite.block.erase: true
     booksuite.sign: true

 booksuite.free:
  description: No cost associated with anything!
  children:
   booksuite.book.free:
    description: Copy and create books for free
   booksuite.block.erase.free:
    description: Don't use water from cauldron when erasing a book

 booksuite.copy.default:
  description: Default copy functions
  children:
   booksuite.copy.other:
    description: Copy all books
    children:
     booksuite.copy.self:
      description: Copy own books
      children:
       booksuite.denynowarn.press: false

 booksuite.command.admin:
  description: All commands
  children:
   booksuite.command.default:
    description: Standard commands
    children:
     booksuite.command.list:
      description: List all .book files in /SavedBooks/
      children:
       booksuite.command: true
     booksuite.command.import:
      description: Make a book from file
      children:
       booksuite.command: true
     booksuite.command.export:
      description: Make a file from book
      children:
       booksuite.command: true
     booksuite.command.edit:
      description: Allow usage of addpage and delpage for book and quill editing
      children:
       booksuite.command: true
     booksuite.command.give:
      description: Allow usage of /book give <player> <book> to import for others
      children:
       booksuite.command: true
   booksuite.command.import.other:
    description: Import a book with an author other than self
    children:
     booksuite.command.import: true
   booksuite.command.unsign.other:
    description: Unsign books by anyone
    children:
     booksuite.command.unsign:
      description: Unsign books by self
      children:
       booksuite.command: true
   booksuite.command.copy.other:
    description: Copy books by anyone
    children:
     booksuite.command.copy:
      description: Copy books by self
      children:
       booksuite.command: true
   booksuite.command.author:
    description: Change author
    children:
     booksuite.command: true
   booksuite.command.title.other:
    description: Re-title books by anyone
    children:
     booksuite.command.title:
      description: Re-title books by self
      children:
       booksuite.command: true
   booksuite.command.delete:
    description: Delete a book from /SavedBooks/
    children:
     booksuite.command: true
   booksuite.command.reload:
    description: Reload the plugin
    children:
     booksuite.command: true
   booksuite.command.update:
    description: Check for updates
    children:
     booksuite.command: true

 booksuite.sign:
  description: All functions available on book signing
  children:
   booksuite.sign.color: true
   booksuite.sign.alias: true

 booksuite.block.erase.other:
  description: Erase others' books
  children:
   booksuite.block.erase:
    description: Erase own books

 booksuite.denynowarn:
  description: Vanilla behavior on attempted usage of "eraser" and "press"
  children:
   booksuite.denynowarn.press:
    description: Crafting bench functions as usual when right clicked with a book - no warning, gui opens.
   booksuite.denynowarn.erase:
    description: Right click cauldron with book does not notify if lacking unsign perms

commands:
 book:
  permission: booksuite.command
  description: BookSuite's universal command
  aliases: [booksuite, bsuite, bs]
