# For more details about the configuration, please see
# http://dev.bukkit.org/bukkit-plugins/booksuite/pages/default-config/
# 

###  ALIASES  ###
# If true, players sign books with their display name.
#
# true
#     - Players sign books as their display name/nick name
#     - Players can unsign books by their display name or login name
enable-aliases: true

###  PERMISSIONS  ###
# If you use a permissions plugin, set to false and assign permissions.
use-inbuilt-permissions: true

###  SAVING  ###
# Should players be able to save private books to /SavedBooks/PlayerName/?
allow-private-saving: true

###  PRINTING PRESS  ###
# Set to false if you do not want to
# allow anyone to use printing presses.
enable-printing-presses: true

###  ERASER  ###
# Same deal as presses.
enable-erasers: true

###  MAIL  ###
# You know the drill.
enable-mail: true

###  RULES  ###
# If true, /rules, /book rules, and /? will give player
# a copy of the saved rulebook. Set false to slightly
# improve memory usage and disable rules commands.
enable-book-rules: true

###  UPDATE CHECK  ###
update-check: true
login-update-check: true

###  DEBUG  ###
# This option will print out a trace of non-gamebreaking errors.
debug-mode: false
