# For more details about the configuration, please see
# http://dev.bukkit.org/server-mods/booksuite/pages/default-config/
# 
# 
# Because of the way multiple copies are handled, copying is capped to
# 10 by default. High numbers WILL lead to server lag on usage.
# Also, how many of the same book do you really need?
# 
# This measure is temporary and will be removed in the next build.
# The only reason a feature so badly coded is included is because
# this release has been rushed by bugs.
# 
maximum-copies-per-operation: 10

###  ALIASES  ###
# Aliases are names people are allowed to sign books with
# and authors whose books they can unsign.
#
# Modes:
# none
#     - Vanilla book signing behavior
# default
#     - Players sign books as their display name/nick name
#     - Players can unsign books by their display name or login name
# multi
#     - Players sign books as their set alias (defaults to display name)
#     - Players can unsign books by any of their aliases
#     - Aliases can be added with /book alias add <alias>
#     - Aliases can be set (used for signing) with /book alias <alias>
#     - Aliases are stored in aliases.yml
alias-mode: default

###  PERMISSIONS  ###
# If you use a permissions plugin, set to false and assign permissions.
use-inbuilt-permissions: true

###  SAVING  ###
# Should players be able to save private books to /SavedBooks/PlayerName/?
allow-private-saving: true

###  PRINTING PRESS  ###
# Set to false if you do not want to
# allow anyone to use printing presses.
enable-printing-presses: true

###  ERASER  ###
# Same deal as presses.
enable-erasers: true

###  RULES  ###
# If true, /rules, /book rules, and /? will give player
# a copy of the saved rulebook. Set false to slightly
# improve memory usage and disable rules commands.
enable-book-rules: true

###  METRICS  ###
# Please do not disable metrics, being able to see that there are
# servers using BookSuite encourages me to develop it further.
enable-metrics: true

###  UPDATE CHECK  ###
update-check: true
allow-update-command: true
login-update-check: true
