###PERMISSIONS###
use-external-permissions: true

###METRICS###
enable-metrics: true

###UPDATE CHECK###
# if true, players with the ability to use the update check
# command will automatically trigger a check on login
login-update-check: true

###ALIASES###
# Aliases are names people are allowed to sign books with
# and authors whose books they can unsign.
#
# Modes:
# none
#     - Vanilla book signing behavior
# default
#     - Players sign books as their display name/nick name
#     - Players can unsign books by their display name or login name
# multi
#     - Players sign books as their set alias (defaults to display name)
#     - Players can unsign books by any of their aliases
#     - Aliases can be added with /book alias add <alias>
#     - Aliases can be set (used for signing) with /book alias <alias>
alias-mode: default
