name: BookSuite

main: com.github.Jikoo.BookSuite.BookSuite
version: 3.0.0
author: Adam Gunn (PlanarWarp)  Ted Meyer (tmathmeyer)

permissions:
    booksuite.*:
        description: Everything bookish and sweet!
        children:
            booksuite.book.free: true
            booksuite.copy.other: true
            booksuite.command.makebook: true
            booksuite.mail.send: true
            booksuite.mail.receive: true
            booksuite.mail.all: true
            booksuite.mail.attach: true
            booksuite.mail.attach.self: true
    booksuite.free:
        description: No cost associated with getting a book!
    booksuite.mail.send:
        description: Send mail with a right click!
    booksuite.mail.all:
        description: Global mailing!
    booksuite.mail.receive:
        description: can check/receive non-global (personal) mail
    booksuite.mail.attach:
        description: send items with mail!
    booksuite.mail.attach.self:
        description: mail self items - Enable with caution, can be used as a personal enderchest with no space limit.
    booksuite.copy.self:
        description: copy own books
        children:
            booksuite.copy.deny: false
            booksuite.copy.deny.nowarn: false
    booksuite.copy.other:
        description: copy all books
        children:
            booksuite.copy.self: true
    booksuite.copy.deny:
        description: Deny book copying, send deny message
        children:
            booksuite.copy.deny.nowarn: false
    booksuite.copy.deny.nowarn:
        description: Crafting bench functions as usual when right clicked with a book - no warning, gui opens.
    booksuite.command.makebook:
        description: make a book from file
commands:
   makebook:
      description: makes a book from markuptextfile
      permission: booksuite.command.makebook
      permission-message: You don't have <permission>
