name: BookSuite

main: com.github.Jikoo.BookSuite.BookSuite
version: 2.1.0
author: Adam Gunn (Planar Warp)  Ted Meyer (tmathmeyer)

permissions:
    booksuite.*:
        description: Everything bookish and sweet!
        children:
            booksuite.book.free: true
            booksuite.copy.other: true
            booksuite.command.makebook: true
    booksuite.free:
        description: No cost associated with getting a book!
    booksuite.copy.self:
        description: copy own books
        children:
            booksuite.copy.deny: false
            booksuite.copy.deny.nowarn: false
    booksuite.copy.other:
        description: copy all books
        children:
            booksuite.copy.self: true
    booksuite.copy.deny:
        description: Deny book copying
        children:
            booksuite.copy.deny.nowarn: false
    booksuite.copy.deny.nowarn:
        description: Crafting bench functions as usual when right clicked with a book - no warning, gui opens.
    booksuite.command.makebook:
        description: make a book from file
commands:
   makebook:
      description: makes a book from markuptextfile
      permission: booksuite.command.makebook
      permission-message: You don't have <permission>
