name: BookSuite

main: com.github.Jikoo.BookSuite.BookSuite
version: 1.1.1
author: Adam Gunn (Planar Warp)  Ted Meyer (tmathmeyer)

permissions:
    booksuite.*:
        description: Everything bookish and sweet!
        children:
            booksuite.free: true
            booksuite.other: true
            booksuite.copy: true
            booksuite.makebook: true
    booksuite.free:
        description: allows users to copy all books with the printing press block
        default: op
    booksuite.other:
        description: books for free! :D
        default: op
    booksuite.copy:
        description: can do ANY copying
        default: true
    booksuite.makebook:
        description: make a book from file
        default: true
commands:
   makebook:
      description: makes a book from markuptextfile
      usage: /makebook booktitle url
      permission: booksuite.makebook
      permission-message: You don't have <permission>
