name: BookSuite

main: com.github.Jikoo.BookSuite.BookSuite
version: 1.1.1
author: Jikoo (Planar Warp)

permissions:
    booksuite.*:
        description: Everything bookish and sweet!
        children:
            booksuite.free: true
            booksuite.other: true
            booksuite.copy: true
    booksuite.free:
        description: allows users to copy all books with the printing press block
        default: op
    booksuite.other:
        description: books for free! :D
        default: op
    booksuite.copy:
        description: can do ANY copying
        default: true
